# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-06 19:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('desc', models.TextField(max_length=300, verbose_name='\u7b80\u4ecb')),
                ('profession', models.CharField(max_length=50, verbose_name='\u4e13\u4e1a')),
                ('year', models.CharField(choices=[('1', '2018\u5c4a'), ('2', '2017\u5c4a'), ('3', '2016\u5c4a'), ('4', '2015\u5c4a')], default='1', max_length=10, verbose_name='\u5e74\u7ea7')),
            ],
            options={
                'verbose_name': '\u4f5c\u8005',
                'verbose_name_plural': '\u4f5c\u8005',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('desc', models.CharField(max_length=100, verbose_name='\u63cf\u8ff0')),
                ('content', models.TextField(max_length=5000, verbose_name='\u5185\u5bb9')),
                ('image', models.ImageField(upload_to='/interview/%Y/%m', verbose_name='\u5c01\u9762')),
                ('company', models.CharField(max_length=50, verbose_name='\u516c\u53f8')),
                ('trade', models.CharField(choices=[('t1', '\u4e92\u8054\u7f51'), ('t2', '\u7f51\u7edc\u5b89\u5168'), ('t3', '\u8fd0\u8425\u5546'), ('t4', '\u94f6\u884c'), ('t5', '\u96c6\u6210\u5546'), ('t6', '\u56fd\u4f01'), ('t7', '\u4e91\u8ba1\u7b97'), ('t8', '\u5176\u4ed6')], default='t1', max_length=10, verbose_name='\u884c\u4e1a')),
                ('location', models.CharField(choices=[('l1', '\u4e0a\u6d77'), ('l2', '\u5317\u4eac'), ('l3', '\u5e7f\u5dde'), ('l4', '\u6df1\u5733'), ('l5', '\u5168\u56fd'), ('l6', '\u5176\u4ed6')], default='l1', max_length=10, verbose_name='\u5730\u533a')),
                ('pub_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('read_count', models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u6b21\u6570')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Author', verbose_name='\u6240\u5c5e\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u9762\u8bd5\u7ecf\u9a8c',
                'verbose_name_plural': '\u9762\u8bd5\u7ecf\u9a8c',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('email', models.CharField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('password', models.CharField(max_length=128, verbose_name='\u5bc6\u7801')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=10, verbose_name='\u6027\u522b')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/%Y/%m', verbose_name='\u5934\u50cf')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
    ]
