# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-08 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='image',
            field=models.ImageField(upload_to='interview/%Y/%m', verbose_name='\u5c01\u9762'),
        ),
    ]
