# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-22 15:38
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20180608_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u5185\u5bb9'),
        ),
    ]
